# Generated by Django 5.0.14 on 2026-04-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_url', models.URLField(blank=True, max_length=500, verbose_name='URL del arte/diseño')),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='campaigns.campaign')),
                ('space_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='spaces.spacerental')),
            ],
        ),
    ]
