# Generated by Django 5.0.14 on 2026-04-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectortask',
            options={'ordering': ['-id']},
        ),
    ]
