# Generated by Django 5.0.14 on 2026-04-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_desc', models.TextField(verbose_name='Descripción de ubicación')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('dimensions', models.CharField(help_text='Ej: 4x3m', max_length=100)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('activo', 'Activo'), ('finalizado', 'Finalizado')], default='reservado', max_length=20)),
                ('ad_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='spaces.adspace')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='clients.client')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals_linked', to='work_orders.workorder')),
            ],
        ),
    ]
