# Generated by Django 5.0.14 on 2026-04-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre completo / Razón Social')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spacerental',
            name='ad_space',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Esquina Ruta 8 y 197', max_length=255, verbose_name='Nombre descriptivo')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/locations/')),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rent_period', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='spaces.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Monoposte Principal', max_length=255, verbose_name='Identificador')),
                ('type', models.CharField(choices=[('monoposte', 'Monoposte'), ('frontlight', 'Frontlight'), ('pantalla_led', 'Pantalla LED'), ('pared', 'Pared/Medianera'), ('otro', 'Otro')], default='monoposte', max_length=20)),
                ('dimensions', models.CharField(blank=True, help_text='Ej: 4x3m', max_length=100, null=True)),
                ('photos', models.JSONField(blank=True, default=list, help_text='URLs de fotos')),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='spaces.location')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('alquiler', 'Alquiler Terreno'), ('luz', 'Luz / Energía'), ('seguro', 'Seguro'), ('impuesto', 'Impuesto Municipal'), ('mantenimiento', 'Mantenimiento / Reparación'), ('otro', 'Otro')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/spaces/')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='spaces.location')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='spaces.structure')),
            ],
        ),
        migrations.CreateModel(
            name='StructureFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Cara Norte, Cara Sur, Principal', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='spaces.structure')),
            ],
        ),
        migrations.AddField(
            model_name='spacerental',
            name='face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='spaces.structureface'),
        ),
        migrations.DeleteModel(
            name='AdSpace',
        ),
    ]
