# Generated by Django 5.0.14 on 2026-04-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_landlord_remove_spacerental_ad_space_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='rent_period',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('por_contrato', 'Por Contrato')], default='mensual', max_length=20),
        ),
    ]
