# Generated by Django 5.0.14 on 2026-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_location_rent_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='location',
            name='expiration_alert_active',
            field=models.BooleanField(default=True, verbose_name='Alertas activadas'),
        ),
        migrations.AddField(
            model_name='location',
            name='expiration_alert_days_before',
            field=models.IntegerField(default=30, help_text='Días antes del vencimiento para empezar a alertar'),
        ),
        migrations.AddField(
            model_name='location',
            name='expiration_alert_frequency',
            field=models.IntegerField(default=7, help_text='Frecuencia de alerta en días (ej: cada 7 días)'),
        ),
    ]
