# Generated by Django 5.0.14 on 2026-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='photos',
        ),
        migrations.AddField(
            model_name='structure',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='structures/photos/', verbose_name='Foto de instalación'),
        ),
    ]
