# Generated by Django 5.0.14 on 2026-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_add_photo_to_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidad'),
        ),
    ]
