# Generated by Django 5.0.14 on 2026-04-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_location_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('monoposte', 'Monoposte'), ('frontlight', 'Frontlight'), ('backlight', 'Backlight'), ('pantalla_led', 'Pantalla LED'), ('medianera', 'Medianera'), ('refugio', 'Refugio'), ('columna', 'Columna'), ('cartelera_simple', 'Cartelera simple'), ('otro', 'Otro')], default='monoposte', max_length=20),
        ),
    ]
