# Generated by Django 5.0.14 on 2026-04-28 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('clients', '0002_alter_client_options'),
        ('spaces', '0007_alter_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacerental',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_rentals', to='campaigns.campaign', verbose_name='Campaña vinculada'),
        ),
        migrations.AddField(
            model_name='structure',
            name='led_total_seconds_per_hour',
            field=models.IntegerField(blank=True, default=3600, help_text='Segundos vendibles por hora para pantallas LED (3600 = 100%)', null=True),
        ),
        migrations.CreateModel(
            name='LEDSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, help_text='Duración del spot', max_digits=10)),
                ('time_unit', models.CharField(choices=[('segundos', 'Segundos'), ('minutos', 'Minutos'), ('horas', 'Horas')], default='segundos', max_length=20)),
                ('repetitions_per_hour', models.IntegerField(default=1, help_text='Cuántas veces se reproduce por hora')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='activo', max_length=20)),
                ('creative_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_slots', to='campaigns.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_slots', to='clients.client')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_slots', to='spaces.structure')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
