# Generated by Django 5.0.14 on 2026-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_spacerental_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledslot',
            name='hour_from',
            field=models.IntegerField(blank=True, help_text='Hora de inicio de la franja (0-23). Null = toda la jornada', null=True),
        ),
        migrations.AddField(
            model_name='ledslot',
            name='hour_to',
            field=models.IntegerField(blank=True, help_text='Hora de fin de la franja (0-23, exclusivo). Null = toda la jornada', null=True),
        ),
    ]
