# Generated by Django 5.0.14 on 2026-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_ledslot_hour_from_hour_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='led_operating_hours',
            field=models.IntegerField(blank=True, default=24, help_text='Horas por día que opera la pantalla LED (1-24)', null=True),
        ),
    ]
