# Generated by Django 5.0.14 on 2026-04-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0010_structure_led_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceexpense',
            name='period_from',
            field=models.DateField(blank=True, help_text='Inicio del período que cubre este gasto', null=True),
        ),
        migrations.AddField(
            model_name='spaceexpense',
            name='period_to',
            field=models.DateField(blank=True, help_text='Fin del período que cubre este gasto', null=True),
        ),
        migrations.AlterField(
            model_name='spaceexpense',
            name='date',
            field=models.DateField(help_text='Fecha de pago o registro'),
        ),
    ]
