# Generated by Django 5.0.14 on 2026-04-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0011_spaceexpense_period_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceexpense',
            name='expense_type',
            field=models.CharField(choices=[('alquiler', 'Alquiler Terreno'), ('luz', 'Luz / Energía'), ('seguro', 'Seguro'), ('impuesto', 'Impuesto Municipal'), ('mantenimiento', 'Mantenimiento / Reparación'), ('instalacion', 'Instalación de Estructura'), ('reparacion', 'Reparación de Estructura'), ('otro', 'Otro')], max_length=20),
        ),
    ]
