# Generated by Django 5.0.14 on 2026-04-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0012_add_instalacion_reparacion_expense_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_date', models.DateField(verbose_name='Inicio del contrato')),
                ('contract_end_date', models.DateField(verbose_name='Vencimiento del contrato')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de alquiler')),
                ('rent_period', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('por_contrato', 'Por Contrato')], default='mensual', max_length=20, verbose_name='Período de pago')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/locations/history/', verbose_name='Archivo del contrato')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='spaces.location', verbose_name='Terreno')),
            ],
            options={
                'ordering': ['-contract_start_date'],
            },
        ),
    ]
