# Generated by Django 5.0.14 on 2026-04-21 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Null = producto compartido/global disponible para todos los sectores', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='production.sector'),
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('is_cross_sector', models.BooleanField(default=False, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_approvals', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.product')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
                ('sector_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='production.sectortask')),
            ],
            options={
                'permissions': [('approve_material_reservation', 'Puede aprobar/rechazar reservas de material')],
                'unique_together': {('sector_task', 'product')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.materialreservation'),
        ),
    ]
