# Generated by Django 5.0.14 on 2026-04-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_sector_material_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio promedio ponderado de costo — visible solo para admins', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario de compra (solo en ingresos). Actualiza el promedio ponderado del producto.', max_digits=12, null=True),
        ),
    ]
