# Generated by Django 5.0.14 on 2026-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchase_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del precio promedio ponderado del producto al momento del egreso. Permite calcular el costo real de materiales usados en OTs.', max_digits=12, null=True),
        ),
    ]
