# Generated by Django 5.0.14 on 2026-04-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_unit_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asset_status',
            field=models.CharField(blank=True, choices=[('activa', 'Activa'), ('en_reparacion', 'En reparación'), ('baja', 'Baja')], default='activa', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('material', 'Material de producción'), ('insumo', 'Insumo'), ('herramienta', 'Herramienta')], default='material', help_text='material = producción (OTs), insumo = consumible, herramienta = activo patrimonial', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
