# Generated by Django 5.0.14 on 2026-04-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_kind_herramienta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
