# Generated by Django 5.0.14 on 2026-04-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialreservation',
            unique_together=set(),
        ),
    ]
