# Generated by Django 5.0.14 on 2026-04-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('inventory', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_linked', to='work_orders.workorder'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budget'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='inventory.product'),
        ),
    ]
