# Generated by Django 5.0.14 on 2026-04-20 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='budget',
            name='issue_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de emisión'),
            preserve_default=False,
        ),
    ]
