# Generated by Django 5.0.14 on 2026-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_expiry_date_budget_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('facturado', 'Facturado'), ('vencido', 'Vencido')], default='borrador', max_length=20),
        ),
    ]
