# Generated by Django 5.0.14 on 2026-04-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
    ]
