# Generated by Django 5.0.14 on 2026-04-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_alter_budget_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='work_order',
        ),
    ]
