# Generated by Django 5.0.14 on 2026-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_remove_budget_work_order_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='iva_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IVA %'),
        ),
    ]
