# Generated by Django 5.0.14 on 2026-04-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_add_iva_pct_to_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='government_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Orden de Compra / Gubernamental'),
        ),
    ]
