# Generated by Django 5.0.14 on 2026-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_budget_government_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='billing_type',
            field=models.CharField(choices=[('factura', 'Factura'), ('remito', 'Remito')], default='factura', max_length=20, verbose_name='Tipo de Facturación'),
        ),
    ]
