# Generated by Django 5.0.14 on 2026-04-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='photos_after',
            field=models.JSONField(blank=True, default=list, help_text='Fotos de trabajo terminado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='photos_before',
            field=models.JSONField(blank=True, default=list, help_text='Fotos de diseño / antes de producción'),
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_uses', to='inventory.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='work_orders.workorder')),
            ],
            options={
                'unique_together': {('work_order', 'product')},
            },
        ),
    ]
