# Generated by Django 5.0.14 on 2026-04-20 15:17

import django.db.models.deletion
import work_orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_workorder_photos_after_workorder_photos_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs (Legacy)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='photos_after',
            field=models.JSONField(blank=True, default=list, help_text='Fotos de trabajo terminado (Legacy)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='photos_before',
            field=models.JSONField(blank=True, default=list, help_text='Fotos de diseño / antes de producción (Legacy)'),
        ),
        migrations.CreateModel(
            name='WorkOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=work_orders.models.work_order_photo_path)),
                ('category', models.CharField(choices=[('before', 'Antes/Diseño'), ('after', 'Después/Terminado')], default='before', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_photos', to='work_orders.workorder')),
            ],
        ),
    ]
