# Generated by Django 5.0.14 on 2026-04-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_status'),
        ('work_orders', '0003_alter_workorder_photos_alter_workorder_photos_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='budget',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_assigned', to='budgets.budget'),
        ),
    ]
