# Generated by Django 5.0.14 on 2026-04-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_alter_workorder_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrderMaterial',
        ),
    ]
