# Generated by Django 5.0.14 on 2026-04-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0007_workorder_add_entregada_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('entregada', 'Entregada'), ('facturada', 'Facturada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
