# Generated by Django 5.0.14 on 2026-04-23 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0008_workorder_add_facturada_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workordernotification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workordernotification',
            name='kind',
            field=models.CharField(choices=[('nueva_ot', 'Nueva OT'), ('lista_para_facturar', 'Lista para facturar')], default='nueva_ot', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='workordernotification',
            unique_together={('user', 'work_order', 'kind')},
        ),
    ]
