# Generated by Django 5.0.14 on 2026-04-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0009_workordernotification_add_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='photos_after',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='photos_before',
        ),
    ]
