# Generated by Django 5.0.14 on 2026-04-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_add_photo_to_structure'),
        ('work_orders', '0010_remove_legacy_photo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_work_orders', to='spaces.structure', verbose_name='Estructura vinculada'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(choices=[('general', 'General'), ('instalacion_espacio_vial', 'Instalación Espacio Vial'), ('mantenimiento_espacio_vial', 'Mantenimiento Espacio Vial'), ('campana', 'Campaña'), ('civil', 'Civil / Construcción'), ('electrico', 'Eléctrico')], default='general', max_length=30, verbose_name='Tipo de OT'),
        ),
    ]
