# Generated by Django 5.0.14 on 2026-04-28 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('work_orders', '0011_add_work_type_and_structure_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='campaigns.campaign', verbose_name='Campaña vinculada'),
        ),
    ]
