# Generated by Django 5.0.14 on 2026-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfil_sectormembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ceo', 'CEO'), ('admin', 'Admin'), ('empleado', 'Empleado')], default='empleado', max_length=20),
        ),
    ]
