# Generated by Django 5.0.14 on 2026-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_hr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
