# Generated by Django 5.0.14 on 2026-04-22 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_orders', '0005_remove_workordermaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('insumo', 'Insumo'), ('servicio', 'Servicio'), ('alquiler', 'Alquiler'), ('otro', 'Otro')], default='insumo', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_registered', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, help_text='OT a la que se imputa el gasto. Null = gasto general del período.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='work_orders.workorder')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
