# Generated by Django 5.0.14 on 2026-04-28 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_add_iva_pct_to_budget'),
        ('finanzas', '0003_expense_add_herramienta_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IvaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.DateField(help_text='Fecha de facturación (para agrupar por mes)')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de declarar'), ('declarado', 'Declarado/Pagado a AFIP')], default='pendiente', max_length=20)),
                ('declared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iva_record', to='budgets.budget')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iva_records_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period', '-created_at'],
            },
        ),
    ]
