# Generated by Django 5.0.14 on 2026-05-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CUIT/CUIL'),
        ),
    ]
